### ISSUE TITLE
Massive amount of JEI errors

### ISSUE THREAD

**Issue by Darkere** [Yamahari/ILikeWood#10]
You know a couple of errors are fine but at multiple thousand lines, it becomes a problem.

Example log: https://gist.githubusercontent.com/Nyanmaster/8f8d67d098ef603b5a7073c8bbd7cbb8/raw/fda586f1b5878a619d766425db753ccd3ac072b8/Latest.log

**Comment by Yamahari** [comment]
What version are you using? I think this is already fixed in 1.15.2-2.2.0.1

**Comment by Darkere** [comment]
The one time I forget to double check for updates...

Yep already fixed. Ty.
