### ISSUE TITLE
JEI support for crafting tables

### ISSUE THREAD

**Issue by SilentChaos512** [Yamahari/ILikeWood#18]
JEI support to allow ingredients to be transferred into the crafting grid (the '+' button in JEI) would be nice. This is fairly easy to implement. I would ask for a recipe book button as well, but... yeah, I know from experience what that's like.

If you'd like, I could do a quick PR to add this for you. Just let me know.

**Comment by Yamahari** [comment]
Feel free :)

**Comment by Yamahari** [comment]
Oh yea and the I don't think it's even possible to add a recipe book to custom crafting tables without rewriting the entire recipe book vanilla code. I already tried when I added the crafting tables :D

**Comment by SilentChaos512** [comment]
I'll wait for JEI to update then, just in case the API changes.

**Comment by Yamahari** [comment]
there's also a PR for better recipe book support, so I might have a look at adding that nonetheless

**Comment by ProsperCraft** [comment]
Came to report that you can't shift-click recipes into the crafting tables, but looks like this is already being handled.

**Comment by Yamahari** [comment]
forgot to close :)
