### ISSUE TITLE
Can't make tools with the new sticks

### ISSUE THREAD

**Issue by Neffrex** [Yamahari/ILikeWood#22]
Can't craft tools with the new sticks
![2019-06-27_18 59 13](https://user-images.githubusercontent.com/52071446/60285256-d1809400-990d-11e9-8b34-0e1783afd922.png)

**Comment by kotelkonrad** [comment]
Very bad

**Comment by Yamahari** [comment]
you can craft my sticks into vanilla sticks 1:1 for now

**Comment by Yamahari** [comment]
duplicate suggestion

**Comment by sdaddy** [comment]
> you can craft my sticks into vanilla sticks 1:1 for now, like with every other block of mine

How?
I'm using ilikewood-release-1.14.3-19w26c and I've tried putting the sticks/chests into every crafting slot.

**Comment by Yamahari** [comment]
Try if it works in a new world

**Comment by sdaddy** [comment]
In a new Single Player world the dark oak sticks converted to normal sticks. I didn't test anything beyond that.

What can I do to fix the problem on my dedicated server that I already added the mod to?
I've worked around the sticks issue by using bamboo, but hoppers and other recipes require vanilla chests which I'm currently only able to get by cheating in.

**Comment by Yamahari** [comment]
no idea what you can do for the dedicated server, i haven't worked much with dedicated servers. Maybe your server has an old version of my mod data pack. Other than that starting a new world on the server should fix the recipes.

**Comment by Neffrex** [comment]
I've notice one think, if you add the mod in worlds pre-created without it, some recipes may bug, I tested with 3 of my old Survivals with no mods and in all of them some recipes were bugged, all the Worlds tested on SinglePlayer.

**Comment by Yamahari** [comment]
but only the vanilla recipes I changed right? my custom recipes work don't they. I think that's a forge bug

**Comment by sdaddy** [comment]
Yes. I can make all of your custom items and blocks, just can't turn them back to the vanilla counterparts. The vanilla recipes worked in single player.

I started the world on the server as a vanilla 1.14.3 and then added Forge soon after. Not sure if that would have anything to do with it.

Would there be a way to maybe add a datapack to add your vanilla recipes in?

**Comment by Yamahari** [comment]
hm, the "/recipe take *"
maybe the game registered the old recipes to your player

**Comment by sdaddy** [comment]
Unfortunately that didn't work.

**Comment by Yamahari** [comment]
I think I found a fix for this btw, you have to run the /datapack command to disable the vanilla data pack, the re-enable it and everything should work. Better late than never!
