### ISSUE TITLE
[SUGGESTION] Crafting fences with new sticks 

### ISSUE THREAD

**Issue by Neffrex** [Yamahari/ILikeWood#24]
I'd like to craft the fences with its relevant sticks instead of the vanilla ones.
![2019-06-27_21 06 11](https://user-images.githubusercontent.com/52071446/60293598-d2222600-991f-11e9-89a7-e0d8beadb034.png)
![2019-06-27_21 09 31](https://user-images.githubusercontent.com/52071446/60293642-e9611380-991f-11e9-9b89-dd0b7e6e6d25.png)

**Comment by Yamahari** [comment]
done
