### ISSUE TITLE
Not Working on Server

### ISSUE THREAD

**Issue by KiritoGames20** [Yamahari/ILikeWood#3]
Keeps crashing on a Server, but works fine in Singleplayer.
Using Forge version 26.0.32 both Singleplayer and Server.

[latest.log](https://github.com/Yamahari/ILikeWood/files/3303262/latest.log)

**Comment by Yamahari** [comment]
think I fixed it, gonna upload new version later today

**Comment by Yamahari** [comment]
new version if out, let me know if it fixed your issues

**Comment by KiritoGames20** [comment]
Thank you,
Works great now, even though I had to install the newer Forge version, as I were gettings bugs when placing the blocks with other mods loaded which caused the blocks to be other mod blocks.
