### ISSUE TITLE
Chests don't make double chests when put next to eachother.

### ISSUE THREAD

**Issue by ProsperCraft** [Yamahari/ILikeWood#33]
**Screenshots**
![2019-06-30_13 37 18](https://user-images.githubusercontent.com/4427684/60401339-19d1c900-9b3d-11e9-918d-f557d318f347.png)

**Comment by Yamahari** [comment]
are they the same type? did you shift click when placing?

**Comment by ProsperCraft** [comment]
ahh, new mechanic, don't place chests while sneaking.
