### ISSUE TITLE
Recipe book on the Crafting Benches

### ISSUE THREAD

**Issue by Neffrex** [Yamahari/ILikeWood#4]
There is no recipe book on the Crafting Benches unlike the normal Crafting Bench, I don't know if it's working as intended or it's a bug but I'd like to have it on those too.
![2019-06-21_13 02 52](https://user-images.githubusercontent.com/52071446/59918518-3d05c580-9425-11e9-9a65-1306d5ffd07f.png)
![2019-06-21_13 02 54](https://user-images.githubusercontent.com/52071446/59918519-3d05c580-9425-11e9-8139-c98d6b568e93.png)
![2019-06-21_13 02 56](https://user-images.githubusercontent.com/52071446/59918520-3d05c580-9425-11e9-86b6-0f967f95ffcd.png)
![2019-06-21_13 02 46](https://user-images.githubusercontent.com/52071446/59918521-3d05c580-9425-11e9-8adb-cc8101367e54.png)
![2019-06-21_13 02 48](https://user-images.githubusercontent.com/52071446/59918522-3d9e5c00-9425-11e9-9dc5-98a2976932b4.png)
![2019-06-21_13 02 50](https://user-images.githubusercontent.com/52071446/59918523-3d9e5c00-9425-11e9-8e16-0c0180cee1cf.png)

**Comment by Yamahari** [comment]
Working as intented because there's no way to add a recipe book to custom crafting tables without rewriting the entire vanilla code for it atm. :) And I am not doing that
