### ISSUE TITLE
BOP support

### ISSUE THREAD

**Issue by kotelkonrad** [Yamahari/ILikeWood#41]
How everything will be added?

**Comment by Yamahari** [comment]
that would be ~1000 new blocks and items just for mod support...

**Comment by BuilderDan** [comment]
I second that, though, to your benefit a lot of the BOP features were cut. So not as many woods. Aside from that mainly cosmetic and consistency Suggestion. It appears BOP logs can't be stripped with your custom axes. Would love for support on that at least!

**Comment by kotelkonrad** [comment]
Omg
