### ISSUE TITLE
Recipe restrictions prevents use of modded woods

### ISSUE THREAD

**Issue by BK119** [Yamahari/ILikeWood#42]
Your recipe restrictions prevent people from making vanilla materials out of modded resources

Can't make chests or sticks, which is quite a big deal

Simple fix, remove the restrictions or add config options to do so ourselves

**Comment by Yamahari** [comment]
you can turn my items into their vanilla counterpart by placing them in a crafting grid

**Comment by BK119** [comment]
I’m not talking about your sticks.

Your mod disables the standard recipes. That prevents me from using other mod woods to create things, because they rely on those default recipes

For example, I can’t turn fir planks (From BoP) into sticks because you disabled the recipe. The only way to make vanilla sticks is with your sticks

**Comment by Yamahari** [comment]
Ah now I get it, for now you can just delete the minecraft recipes in my datapack

**Comment by Yamahari** [comment]
that's gonna be tricky to fix. I am working on BoP support atm. so those wood variants won't be a problem anymore.

**Comment by Yamahari** [comment]
BoP woods are added now, should work fine with them, for other wood variants you have to explicitly add them or some nasty hacks are necessary
