### ISSUE TITLE
Wooden Item Usage

### ISSUE THREAD

**Issue by BuilderDan** [Yamahari/ILikeWood#43]
**Describe the bug**
Any wooden tools made with the mod are not able to be used as fuel in furnaces.

**To Reproduce**
1. Make a wooden tool that isn't default
2. Try to use it as fuel
3. Find out you can't

**Expected behavior**
For wooden tools to be used as a fuel source like the default.

**Additional context**
I apologize if this isn't precisely considered a bug, but I wasn't sure if it was really a suggestion either as the base game follows this rule by default.

**Comment by Yamahari** [comment]
sure I'll add it if I can

**Comment by BuilderDan** [comment]
Gonna just expand this thread, it appears you can't make fences or utilize the sticks in any recipes aside from tool making (That I know of). You also can't craft with the Wood Panels. And just to expand on the initial point of this thread, it makes sense to just have everything burnable. Thanks for taking the time to acknowledge my request and I hope these additions aren't too difficult to implement if you choose too!

**Comment by Yamahari** [comment]
Yes you can. I assume you created the world without my mod present? That breaks overriden vanilla recipes. To fix that you need to disable and re-enable the vanilla datapack with the /datapack command

**Comment by BuilderDan** [comment]
Vanilla recipes work fine. Anything that uses the items you implemented does not. Even with /datapack enable Vanilla.

**Comment by Yamahari** [comment]
Can you be more specific about what recipes don't work? They all work fine for others. Also did you *disable* before doing *enable*

**Comment by BuilderDan** [comment]
It couldn't be simpler then it simply does not work. With anything, with the vanilla wood stuff you added nor the BOP stuff added. Can't craft certain things with them or smelt with them at all.
https://i.gyazo.com/069f055865e90d0f3e7fb8aea91d63ae.mp4
I did disable and re-enable the Vanilla pack. No fix.

**Comment by Yamahari** [comment]
https://discord.gg/qn9Aa9u join the discord, i can help more quickly there
Did you try in a new world?

**Comment by Yamahari** [comment]
Can be used as fuel now :)
