### ISSUE TITLE
Remove all recipe overwrite and create a carpentry table for this mod instead. 

### ISSUE THREAD

**Issue by VeloxAzo** [Yamahari/ILikeWood#45]
Recipe overwrite just causes way too many issues. 

For example, I can't use cherrywood (from Forbidden & Arcanus) for anything at all. 

(I had been previously using cherry wood specifically because it had no interactions with ilikewood, but the most recent update broke all the recipes for it on the server I play on)

**Comment by Yamahari** [comment]
mod reworked, also new github https://github.com/Yamahari/I-Like-Wood :) all recipe conflicts should be solved
