### ISSUE TITLE
Incompatible with latest Biomes O'Plenty

### ISSUE THREAD

**Issue by KorDum** [Yamahari/ILikeWood#48]
**Describe the bug**

Latest version of ILikeWood incompatible with latest BOP version. See screenshot below.

**Screenshots**

![image](https://user-images.githubusercontent.com/1331559/62831098-8226c680-bc22-11e9-8e08-0ae9c651559a.png)

**Additional context**
Forge 28.0.45  
BOP 9.0.0.226  
ILikeWood 19w30a

**Comment by frakier** [comment]
I opened the jar in 7-zip, wen into META-INF, opened mods.toml
changed line 55 from...
versionRange="[version]"
to
versionRange="[1.14.4,)"

works... so far

**Comment by Yamahari** [comment]
fixed :)
