### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by HonestAngel** [Yamahari/ILikeWood#9]
[crash-2020-02-25_14.09.51-server.txt](https://github.com/Yamahari/ILikeWood-1.15/files/4252474/crash-2020-02-25_14.09.51-server.txt)

It appears to be an issue with Minecolonies... Added just Minecolonies and your mod and it crashed...
All other mods seem to work fine with it...

[crash-2020-02-25_14.52.03-server.txt](https://github.com/Yamahari/ILikeWood-1.15/files/4252562/crash-2020-02-25_14.52.03-server.txt)

**Comment by Yamahari** [comment]
Seems like minecolonies accesses burn times before configs are loaded, i'll have a look later

**Comment by Yamahari** [comment]
something seems to break when wood type enum gets loaded earlier than expected, don't know what yet

**Comment by HonestAngel** [comment]
I appreciate your help with it. I love your mod. I am sure you will find the problem. Either way I will be patiently waiting. Thank you for your time.

**Comment by Yamahari** [comment]
this should be fixed with new version, feel free to re-open if not :)
